//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Consolidated_ReportingEntities : DbContext
    {
        public Consolidated_ReportingEntities()
            : base("name=Consolidated_ReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Rep_ReportFamilies> Rep_ReportFamilies { get; set; }
        public DbSet<Rep_ReportNames> Rep_ReportNames { get; set; }
        public DbSet<Rep_ReportCategories> Rep_ReportCategories { get; set; }
    
        public virtual ObjectResult<Rep_ReportListforUser_Result> Rep_ReportListforUser(string userName, Nullable<int> familyId, Nullable<int> categoryID)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var familyIdParameter = familyId.HasValue ?
                new ObjectParameter("FamilyId", familyId) :
                new ObjectParameter("FamilyId", typeof(int));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rep_ReportListforUser_Result>("Rep_ReportListforUser", userNameParameter, familyIdParameter, categoryIDParameter);
        }
    }
}
