//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep_Report_Names
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ReportURL { get; set; }
        public string Format { get; set; }
        public Nullable<bool> DateDisabled { get; set; }
    }
}
