//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep_ReportCategories
    {
        public int Id { get; set; }
        public int FamilyID { get; set; }
        public string Category { get; set; }
        public Nullable<int> CategoryType { get; set; }
        public Nullable<int> Tabid { get; set; }
    }
}
