//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep_ReportNames
    {
        public int ReportID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public Nullable<int> ReportOrXL { get; set; }
    }
}
