//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLog
    {
        public int LogID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Level { get; set; }
        public string UserMessage { get; set; }
        public string CallSite { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public string CallingStack { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
